version: "3.9"
services:
  cecy_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cecy
  api_js:
    depends_on:
      - cecy_db
    build: .
    ports:
      - "3000:3000"
